version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: docker
    directory: "/src/test/resources/Dockerfile"
    schedule:
      interval: daily
